name    'vmadman-jira'
version '0.0.1'
source 'https://github.com/vmadman/puppet-confluence'
author 'Luke Chavers <github.com/vmadman>'
license 'Apache License, Version 2.0'
summary 'Module to install Confluence'
description 'Module to install Confluence'
project_page 'https://github.com/vmadman/puppet-confluence'
